version: "3"

services:
  d_api-banco:
    container_name: d_api-banco
    build: .docker/api-banco
    volumes:
      - .docker/api-banco:/api
      - .docker/api-banco/node_modules:/api/node_modules
    ports:
      - "3000:3000"
    networks:
      - d-net

  d_banco-fila:
    container_name: d_banco-fila
    image: "rabbitmq:3.8-management"
    environment:
      - RABBITMQ_ERLANG_COOKIE=fYOaGmG67Py+011XTAM3iw==
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
      - RABBITMQ_DEFAULT_VHOST=/
    ports:
      - "15672:15672"
      - "5672:5672"
    networks:
      - d-net

  d_redis:
    container_name: d_redis
    image: redis:alpine
    ports:
      - "6379:6379"
    depends_on:
      - d_banco-fila
    networks:
      - d-net

networks:
  d-net:
    driver: bridge